config/routes.rb
Tut1::Application.routes.draw do

  get "index/home"

  root 'index#home'

  devise_for :users, path: '',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      password: 'reset_password'
    }

  resources :users

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      
      post 'sales/:id', to: 'sales#create'
      get 'sales/:id', to: 'sales#show'
      get 'sales', to: 'sales#index'
      put 'sales/:id', to: 'sales#update'
    end
  end

end

app/controllers/api/v1/sales_controller.rb
class Api::V1::SalesController < Api::V1::ApiController
  before_action :set_sale, only: [:show, :update, :destroy]

  # GET /sales
  def index
    @sales = Cashbox.where(macaddress: params[:macaddress])[0].sales.order('created_at DESC').limit(500)
  end

  # GET /sales/1
  def show
  end

  # POST /sales
  def create
    if Sale.where(id: params[:id]).length != 0
      set_sale
      if @sale.update(sale_params)
        redirect_to @sale
      else
        render :json => "401", status:401
      end
    else
      @sale = Sale.new(sale_params)
      @sale[:details] = params[:sale][:details]
      @sale.created_at = @sale.created_at.to_i / 1000 #truco sucio
      if not @sale.save
        render :json => "401", status:401
      else
        redirect_to @sale
      end
    end
  end

  # PATCH/PUT /sales/1
  def update
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
      cashbox = Cashbox.find(@sale.cashbox_id.to_s)
      if cashbox[:macaddress] != params[:macaddress]
        @sale = nil
      end
      if @sale == nil
        render :json => "401", status:401
      end
    end

    # Only allow a trusted parameter "white list" through.
    def sale_params
      params.require(:sale).permit(:_id, :user_id, :details, :total, :created_at, :cashbox_id, :cash, :card, :isValid)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/index.html.erb
<h1>Listado de Ventas</h1>
<p>A continuación se listan Ventas los almacenadas en el sistema</p>
<br>

<div class="panel panel-default">
  <div class="panel-heading panel-heading-toolbox">
    <div class="panel-title">
      Listado de Ventas
    </div>
  </div>
  <div class="panel-body">
    
    <table class="table table-hover">
      <thead>
        <tr>
            <th>Fecha</th>
            <th>Caja</th>
            <th>Usuario</th>
            <th>Tarjeta</th>
            <th>Efectivo</th>
            <th>Total</th>
            <th>Estado</th>
        </tr>
      </thead>

      <tbody>
        <% @sales.each do |sale| %>
          <% if not sale.isValid %>
            <tr class="danger">
          <% else %>
            <tr>
          <% end %>
              <td>
                <%= link_to sale_path(sale) do %>
                <%= sale.created_at %>
                <% end %>
              </td>
              <td><%= sale.cashbox %></td>
              <td><%= sale.user %></td>
              <td><%= sale.card %></td>
              <td><%= sale.cash %></td>
              <td><%= sale.total %></td>
              <td>
                <% if sale.isValid == false %>
                  Anulada
                <% else %>
                  Valida
                <% end %>
              </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= will_paginate @sales, renderer: BootstrapPagination::Rails %>

  </div>
</div>

<br>

app/views/sales/show.html.erb
<h1>Detalle de la Venta</h1>
<p>A continuación se muestra la información almacenada de la Venta.</p>
<br>

<div class="panel panel-default">
	<div class="panel-heading panel-heading-toolbox">
		<div class="panel-title">Detalle de la Venta</div>
		<div class="panel-toolbar">
			<%= link_to 'Volver', sales_path, :class => "btn btn-link" %>
		</div>
	</div>
	<div class="panel-body">
		
		<table class="table">
			<tbody>
				<tr>
    				<th>Usuario:</th>
				    <td><%= @sale.user %></td>
				</tr>
				<tr>
				    <th>Fecha:</th>
				    <td><%= @sale.created_at %></td>
				</tr>
				<tr>
				    <th>Caja:</th>
				    <td><%= @sale.cashbox %></td>
				</tr>
				<tr>
					<th>Estado:</th>
					<td>
						<% if @sale.isValid == false %>
		                  Anulada
		                <% else %>
		                  Valida
		                <% end %>
					</td>
				</tr>
				<tr>
				    <th>Efectivo:</th>
				    <td>$<%= @sale.cash %></td>
				</tr>
				<tr>
				    <th>Tarjeta:</th>
				    <td>$<%= @sale.card %></td>
				</tr>
			</tbody>
		</table>
		<table class="table table-bordered">
			<thead>
				<tr>
					<th>Nombre producto</th>
					<th>Marca</th>
					<th>Precio</th>
					<th>Cantidad</th>
					<th>Total</th>
				</tr>
			</thead>
			<tbody>
				<% acum = 0 %>
				<% for d in @sale.details %>
					<tr>
						<td><%= d[:product][:name] %></td>
						<td><%= d[:product][:brand] %></td>
						<td class="text-right">$<%= d[:product][:price] %></td>
						<td class="text-right"><%= d[:amount] %></td>
						<td class="text-right">$<%= d[:product][:price]*d[:amount] %></td>
					</tr>
              		<% acum += d[:product][:price]*d[:amount] %>
            	<% end %>
            	<tr class="active">
            		<td colspan=4></td>
            		<td class="text-right">$<%= acum %></td>
            	</tr>
			</tbody>

		</table>
            
	              

	</div>
</div>